# Generated by Django 4.0.2 on 2022-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='download_url',
            field=models.URLField(default=0, verbose_name='download url'),
            preserve_default=False,
        ),
    ]
