# Generated by Django 4.0.2 on 2022-11-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instapkforcopy_user_pub_instauserforcopy_user_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauserforcopy',
            name='user_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.myinstapage', verbose_name='my user for public'),
        ),
    ]
